M48
; DRILL file KiCad 10.0.3 date 2026-06-06T08:41:36
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-06T08:41:36+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X5.9921Y-3.0472
T2
X5.9495Y-3.7833
X5.9495Y-4.4447
T3
X5.9921Y-3.4252
T4
X6.5311Y-4.3883
X6.5397Y-3.0884
X7.3819Y-3.0906
X7.3819Y-4.3898
M30
